### ISSUE TITLE
Avoid establishing a shared secret for CTAP 2.0 authenticators when hmac-secret is not requested

### ISSUE THREAD

**Issue by jschanck** [jcjones/u2f-hid-rs#341]
In [Bug 1936283](https://bugzilla.mozilla.org/show_bug.cgi?id=1936283) we have an example of an authenticator that returns a COSEKey with the wrong `algorithm` field in its `GetKeyAgreement` response. The authenticator has a built-in fingerprint reader, and does not support the `getPinUvAuthTokenUsingUvWithPermissions` function, so we should not need to establish a shared secret, however we establish one opportunistically in case we need to use the hmac-secret extension:
https://github.com/mozilla/authenticator-rs/blob/1959330d9015645b2bf040f7689b7db1c12f429e/src/ctap2/mod.rs#L293-L295

We should avoid establishing a shared secret for CTAP 2.0 authenticators when hmac-secret is not explicitly requested.

**Comment by Grief** [comment]
@jschanck how complex is the fix? I thought it would be as simple as removing three lines of code, wouldn't it?

**Comment by jschanck** [comment]
This was fixed by #342. The change hasn't been uplifted to Firefox yet, if that's why you're asking about it. I can take it as an action item to cut a new release.

**Comment by Grief** [comment]
@jschanck is it known which release will include the fix? I still have the issue on v137.0b10
